apiVersion: db.isotoma.com/v1alpha1
kind: Database
metadata:
  name: foo
spec:
  provider: postgresql
  connect:
    host: testdb
    port: "5432"
  credentials:
    username:
      value: postgresql
    password:
      value: password
  backupTo:
    s3:
      region: eu-west-1
      bucket: db-operator-test
      prefix: test
  awsCredentials:
    region: eu-west-1
    accessKeyID: xxx
    secretAccessKey: yyy
